<!-- GENERATED by harness webslice: /dev gallery route for slice-attention/qk-explorer.
     Hosts the interactive standalone for Playwright drives and Iris judging.
     Regenerated on every webslice run; edits will be lost. -->
<script lang="ts">
	import Interactive from '../../../../../../sessions/slice-attention/page/interactives/QkExplorer.svelte';
</script>

<svelte:head>
	<title>dev · qk-explorer</title>
</svelte:head>

<main data-gallery="qk-explorer">
	<Interactive />
</main>

<style>
	main {
		min-height: 100vh;
		box-sizing: border-box;
		display: grid;
		place-items: center;
		padding: 1.25rem;
	}
</style>
