<!-- GENERATED by harness webslice: /dev gallery route for dotprod/dot-alignment.
     Hosts the interactive standalone for Playwright drives and Iris judging.
     Regenerated on every webslice run; edits will be lost. -->
<script lang="ts">
	import Interactive from '../../../../../../sessions/dotprod/page/interactives/DotAlignment.svelte';
</script>

<svelte:head>
	<title>dev · dot-alignment</title>
</svelte:head>

<main data-gallery="dot-alignment">
	<Interactive />
</main>

<style>
	main {
		min-height: 100vh;
		box-sizing: border-box;
		display: grid;
		place-items: center;
		padding: 1.25rem;
	}
</style>
