<!-- GENERATED by harness webslice: /dev gallery route for toy/rails-probe.
     Hosts the interactive standalone for Playwright drives and Iris judging.
     Regenerated on every webslice run; edits will be lost. -->
<script lang="ts">
	import Interactive from '../../../../../../sessions/toy/page/interactives/RailsProbe.svelte';
</script>

<svelte:head>
	<title>dev · rails-probe</title>
</svelte:head>

<main data-gallery="rails-probe">
	<Interactive />
</main>

<style>
	main {
		min-height: 100vh;
		box-sizing: border-box;
		display: grid;
		place-items: center;
		padding: 1.25rem;
	}
</style>
