<!-- GENERATED by the harness s5.assemble node for session "dotprod".
     Regenerated on every assembly; edits will be lost. -->
<script lang="ts">
	import SecBeat01 from '../../../../../sessions/dotprod/page/sections/beat-01.md';
	import SecBeat02 from '../../../../../sessions/dotprod/page/sections/beat-02.md';
	import IxBeat02 from '../../../../../sessions/dotprod/page/interactives/DotAlignment.svelte';
	import SecBeat03 from '../../../../../sessions/dotprod/page/sections/beat-03.md';
	import SecBeat04 from '../../../../../sessions/dotprod/page/sections/beat-04.md';
	import SecBeat04b from '../../../../../sessions/dotprod/page/sections/beat-04b.md';
	import extensionsData from '../../../../../sessions/dotprod/page/extensions.json';
	import chaptersData from '../../../../../sessions/dotprod/page/video.json';

	let player: HTMLVideoElement | undefined = $state();
	const chapters: { beatId: string; title: string; startSeconds: number }[] =
		chaptersData.chapters ?? [];

	function seek(seconds: number): void {
		if (player) {
			player.currentTime = seconds;
			player.play();
		}
	}

	function format(seconds: number): string {
		const m = Math.floor(seconds / 60);
		const s = Math.floor(seconds % 60);
		return `${m}:${String(s).padStart(2, '0')}`;
	}
</script>

<svelte:head>
	<title>Night School · dotprod</title>
</svelte:head>

<main>
	<header>
		<p class="wordmark">NIGHT SCHOOL</p>
		<div class="rule" aria-hidden="true"></div>
	</header>

	<section aria-label="video">
		<video
			bind:this={player}
			controls
			preload="metadata"
			src="/media/dotprod/session.mp4"
			crossorigin="anonymous"
		>
			<track kind="captions" src="/media/dotprod/captions.vtt" srclang="en" label="English" default />
		</video>
		{#if chapters.length > 0}
			<ol class="chapters">
				{#each chapters as chapter (chapter.beatId)}
					<li>
						<button type="button" onclick={() => seek(chapter.startSeconds)}>
							<span class="mono">{format(chapter.startSeconds)}</span>
							{chapter.title}
						</button>
					</li>
				{/each}
			</ol>
		{/if}
	</section>

	<section class="prose" aria-label="beat-01" id="sec-beat-01">
		<SecBeat01 />
	</section>
	<section class="prose" aria-label="beat-02" id="sec-beat-02">
		<SecBeat02 />
	</section>
	<section aria-label="interactive beat-02" id="ix-beat-02">
		<IxBeat02 />
	</section>
	<section class="prose" aria-label="beat-03" id="sec-beat-03">
		<SecBeat03 />
	</section>
	<section class="prose" aria-label="beat-04" id="sec-beat-04">
		<SecBeat04 />
	</section>
	<section class="prose" aria-label="beat-04b" id="sec-beat-04b">
		<SecBeat04b />
	</section>

	<section class="extensions" aria-label="extensions">
		<h2 class="still-up">Still up?</h2>
		<p class="ext-sub">
			Pick a door: argue it out with an LLM, read the paper that started all
			this, or build something small before bed.
		</p>
		<div class="lane">
			<h3>Argue it out</h3>
			{#each extensionsData.lanes.llm as item (item.prompt)}
				<div class="ext-card">
					<p class="ext-main">{item.prompt}</p>
					<p class="ext-hint">{item.whatGoodLooksLike}</p>
				</div>
			{/each}
		</div>
		<div class="lane">
			<h3>Read the real thing</h3>
			{#each extensionsData.lanes.papers as paper (paper.url)}
				<div class="ext-card">
					<p class="ext-main"><a href={paper.url} rel="noopener">{paper.title}</a></p>
					<p class="ext-hint">{paper.hook}</p>
				</div>
			{/each}
		</div>
		<div class="lane">
			<h3>Build something</h3>
			{#each extensionsData.lanes.projects as project (project.title)}
				<div class="ext-card">
					<p class="ext-main">{project.title}</p>
					<p class="ext-hint">{project.brief}</p>
				</div>
			{/each}
		</div>
	</section>
</main>

<style>
	main {
		max-width: 46rem;
		margin: 0 auto;
		padding: 3rem 1.5rem 5rem;
		display: flex;
		flex-direction: column;
		gap: 2.5rem;
	}

	.wordmark {
		margin: 0 0 1rem;
		font-family: var(--font-mono), monospace;
		font-size: 0.85rem;
		letter-spacing: 0.45em;
		color: var(--color-brand-periwinkle);
	}

	.rule {
		width: 3.5rem;
		height: 2px;
		border-radius: 1px;
		background: var(--color-brand-mint);
	}

	video {
		width: 100%;
		border-radius: 8px;
		background: var(--color-surface);
	}

	.chapters {
		list-style: none;
		margin: 0.75rem 0 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.chapters button {
		min-height: 44px;
		width: 100%;
		text-align: left;
		background: none;
		border: none;
		color: var(--color-text);
		font-family: var(--font-body), Georgia, serif;
		font-size: 0.95rem;
		cursor: pointer;
		padding: 0.35rem 0.5rem;
		border-radius: 6px;
	}

	.chapters button:hover,
	.chapters button:focus-visible {
		background: var(--color-surface);
	}

	.mono {
		font-family: var(--font-mono), monospace;
		color: var(--color-brand-mint);
		margin-right: 0.75rem;
	}

	.prose :global(h2) {
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 1.4rem;
	}

	.prose :global(blockquote) {
		margin: 1rem 0;
		padding: 0.25rem 0 0.25rem 1rem;
		border-left: 3px solid var(--color-brand-mint);
		font-style: italic;
	}

	.prose :global(p) {
		line-height: 1.65;
	}

	.extensions {
		border-top: 2px solid var(--color-brand-mint);
		padding-top: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	.still-up {
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 1.6rem;
		margin: 0;
	}

	.ext-sub {
		margin: 0;
		color: var(--color-text);
		opacity: 0.75;
		font-style: italic;
	}

	.lane h3 {
		font-family: var(--font-mono), monospace;
		font-size: 0.8rem;
		letter-spacing: 0.2em;
		text-transform: uppercase;
		color: var(--color-brand-periwinkle);
		margin: 0 0 0.5rem;
	}

	.ext-card {
		background: var(--color-surface);
		border-radius: 10px;
		padding: 0.85rem 1rem;
		margin: 0 0 0.6rem;
	}

	.ext-main {
		margin: 0 0 0.35rem;
		line-height: 1.5;
	}

	.ext-main a {
		color: var(--color-brand-mint);
	}

	.ext-hint {
		margin: 0;
		font-size: 0.85rem;
		opacity: 0.7;
		line-height: 1.5;
	}
</style>
