<!-- GENERATED by the harness s5.assemble node for session "dotprod".
     Regenerated on every assembly; edits will be lost. -->
<script lang="ts">
	import SecBeat01 from '../../../../../sessions/dotprod/page/sections/beat-01.md';
	import SecBeat02 from '../../../../../sessions/dotprod/page/sections/beat-02.md';
	import IxBeat02 from '../../../../../sessions/dotprod/page/interactives/DotAlignment.svelte';
	import SecBeat03 from '../../../../../sessions/dotprod/page/sections/beat-03.md';
	import SecBeat04 from '../../../../../sessions/dotprod/page/sections/beat-04.md';
	import SecBeat04b from '../../../../../sessions/dotprod/page/sections/beat-04b.md';
	import extensionsData from '../../../../../sessions/dotprod/page/extensions.json';
	import chaptersData from '../../../../../sessions/dotprod/page/video.json';

	let player: HTMLVideoElement | undefined = $state();
	const chapters: { beatId: string; title: string; startSeconds: number }[] =
		chaptersData.chapters ?? [];
	const videoMinutes = Math.max(1, Math.round((chaptersData.videoSeconds ?? 0) / 60));
	const sectionBeatIds = new Set<string>(["beat-01","beat-02","beat-03","beat-04","beat-04b"]);

	function seek(seconds: number): void {
		if (player) {
			player.currentTime = seconds;
			player.play();
		}
	}

	function format(seconds: number): string {
		const m = Math.floor(seconds / 60);
		const s = Math.floor(seconds % 60);
		return `${m}:${String(s).padStart(2, '0')}`;
	}

	function firstWords(text: string, count = 8): string {
		const words = text.split(/\s+/).filter((word) => word.length > 0);
		if (words.length <= count) return text;
		return words.slice(0, count).join(' ') + '\u2026';
	}
</script>

<svelte:head>
	<title>Night School · dotprod</title>
</svelte:head>

<main>
	<header>
		<p class="wordmark">NIGHT SCHOOL</p>
		<div class="rule" aria-hidden="true"></div>
	</header>

	<section class="video-card" aria-label="video">
		<p class="video-hook">Watch the {videoMinutes}-minute build: How do you score a match between two lists of numbers?</p>
		<video
			bind:this={player}
			controls
			preload="metadata"
			src="/media/dotprod/session.mp4"
			crossorigin="anonymous"
		>
			<track kind="captions" src="/media/dotprod/captions.vtt" srclang="en" label="English" default />
		</video>
		{#if chapters.length > 0}
			<ol class="chapters">
				{#each chapters as chapter (chapter.beatId)}
					<li class="chapter-row">
						<button type="button" onclick={() => seek(chapter.startSeconds)}>
							<span class="mono">{format(chapter.startSeconds)}</span>
							{chapter.title}
						</button>
						{#if sectionBeatIds.has(chapter.beatId)}
							<a class="read-link" href={'#sec-' + chapter.beatId}>read</a>
						{/if}
					</li>
				{/each}
			</ol>
		{/if}
		<a class="skip-chip" href="#extensions">Still up? Skip to the menu</a>
	</section>

	<div class="divider" role="separator">
		<span class="divider-label">Prefer to read? The same build, in prose.</span>
	</div>

	<section class="prose" aria-label="beat-01" id="sec-beat-01">
		<SecBeat01 />
	</section>
	<section class="prose" aria-label="beat-02" id="sec-beat-02">
		<SecBeat02 />
	</section>
	<section aria-label="interactive beat-02" id="ix-beat-02">
		<IxBeat02 />
	</section>
	<section class="prose" aria-label="beat-03" id="sec-beat-03">
		<SecBeat03 />
	</section>
	<section class="prose" aria-label="beat-04" id="sec-beat-04">
		<SecBeat04 />
	</section>
	<section class="prose" aria-label="beat-04b" id="sec-beat-04b">
		<SecBeat04b />
	</section>

	<section class="extensions" aria-label="extensions" id="extensions">
		<h2 class="still-up">Still up?</h2>
		<p class="ext-sub">
			Pick one door, not all three: argue it out with an LLM, read the paper
			that started all this, or build something small before bed. One is
			plenty. This is dessert, not homework.
		</p>
		<div class="lanes">
			<div class="lane">
				<h3>Argue it out</h3>
				{#each extensionsData.lanes.llm as item (item.prompt)}
					<details class="ext-item">
						<summary>{firstWords(item.prompt)}</summary>
						<p class="ext-main">{item.prompt}</p>
						<p class="ext-hint">{item.whatGoodLooksLike}</p>
					</details>
				{/each}
			</div>
			<div class="lane">
				<h3>Read the real thing</h3>
				{#each extensionsData.lanes.papers as paper (paper.url)}
					<details class="ext-item">
						<summary>{firstWords(paper.title)}</summary>
						<p class="ext-main"><a href={paper.url} rel="noopener">{paper.title}</a></p>
						<p class="ext-hint">{paper.hook}</p>
					</details>
				{/each}
			</div>
			<div class="lane">
				<h3>Build something</h3>
				{#each extensionsData.lanes.projects as project (project.title)}
					<details class="ext-item">
						<summary>{firstWords(project.title)}</summary>
						<p class="ext-main">{project.title}</p>
						<p class="ext-hint">{project.brief}</p>
					</details>
				{/each}
			</div>
		</div>
	</section>
</main>

<style>
	main {
		max-width: 46rem;
		margin: 0 auto;
		padding: 3rem 1.5rem 5rem;
		display: flex;
		flex-direction: column;
		gap: 2.5rem;
	}

	.wordmark {
		margin: 0 0 1rem;
		font-family: var(--font-mono), monospace;
		font-size: 0.85rem;
		letter-spacing: 0.45em;
		color: var(--color-brand-periwinkle);
	}

	.rule {
		width: 3.5rem;
		height: 2px;
		border-radius: 1px;
		background: var(--color-brand-mint);
	}

	.video-card {
		background: var(--color-surface);
		border: 1px solid color-mix(in oklab, var(--color-text) 10%, transparent);
		border-radius: 12px;
		padding: 1rem;
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}

	.video-hook {
		margin: 0;
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 1.05rem;
		line-height: 1.4;
	}

	video {
		width: 100%;
		border-radius: 8px;
		background: var(--color-bg);
	}

	.chapters {
		list-style: none;
		margin: 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.chapter-row {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.chapters button {
		min-height: 44px;
		flex: 1;
		text-align: left;
		background: none;
		border: none;
		color: var(--color-text);
		font-family: var(--font-body), Georgia, serif;
		font-size: 0.95rem;
		cursor: pointer;
		padding: 0.35rem 0.5rem;
		border-radius: 6px;
	}

	.chapters button:hover,
	.chapters button:focus-visible {
		background: color-mix(in oklab, var(--color-text) 8%, transparent);
	}

	.read-link {
		flex: none;
		font-family: var(--font-mono), monospace;
		font-size: 0.75rem;
		color: var(--color-brand-periwinkle);
		text-decoration: none;
		padding: 0.35rem 0.5rem;
		border-radius: 6px;
	}

	.read-link:hover,
	.read-link:focus-visible {
		text-decoration: underline;
	}

	.skip-chip {
		align-self: flex-end;
		font-family: var(--font-mono), monospace;
		font-size: 0.75rem;
		color: var(--color-brand-mint);
		text-decoration: none;
		border: 1px solid color-mix(in oklab, var(--color-brand-mint) 35%, transparent);
		border-radius: 999px;
		padding: 0.3rem 0.75rem;
	}

	.skip-chip:hover,
	.skip-chip:focus-visible {
		border-color: var(--color-brand-mint);
	}

	.divider {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	.divider::before,
	.divider::after {
		content: '';
		flex: 1;
		height: 1px;
		background: color-mix(in oklab, var(--color-text) 12%, transparent);
	}

	.divider-label {
		font-style: italic;
		font-size: 0.9rem;
		opacity: 0.7;
		text-align: center;
	}

	.mono {
		font-family: var(--font-mono), monospace;
		color: var(--color-brand-mint);
		margin-right: 0.75rem;
	}

	section[id] {
		scroll-margin-top: 1.25rem;
	}

	.prose :global(h2) {
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 1.4rem;
	}

	.prose :global(blockquote) {
		margin: 1rem 0;
		padding: 0.25rem 0 0.25rem 1rem;
		border-left: 3px solid var(--color-brand-mint);
		font-style: italic;
	}

	.prose :global(p) {
		line-height: 1.65;
	}

	.prose :global(details.reveal) {
		margin: 1rem 0;
		background: var(--color-surface);
		border: 1px solid color-mix(in oklab, var(--color-brand-mint) 25%, transparent);
		border-radius: 10px;
		padding: 0.6rem 0.9rem;
	}

	.prose :global(details.reveal summary) {
		cursor: pointer;
		color: var(--color-brand-mint);
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 0.95rem;
	}

	.prose :global(details.reveal[open] summary) {
		margin-bottom: 0.5rem;
	}

	.extensions {
		border-top: 2px solid var(--color-brand-mint);
		padding-top: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	.still-up {
		font-family: var(--font-heading), sans-serif;
		font-weight: 600;
		font-size: 1.6rem;
		margin: 0;
	}

	.ext-sub {
		margin: 0;
		color: var(--color-text);
		opacity: 0.75;
		font-style: italic;
	}

	.lanes {
		display: grid;
		grid-template-columns: repeat(3, minmax(0, 1fr));
		gap: 1rem;
		align-items: start;
	}

	@media (max-width: 40rem) {
		.lanes {
			grid-template-columns: 1fr;
		}
	}

	.lane h3 {
		font-family: var(--font-mono), monospace;
		font-size: 0.72rem;
		letter-spacing: 0.14em;
		text-transform: uppercase;
		white-space: nowrap;
		color: var(--color-brand-periwinkle);
		margin: 0 0 0.5rem;
	}

	.ext-item {
		background: var(--color-surface);
		border: 1px solid color-mix(in oklab, var(--color-text) 8%, transparent);
		border-radius: 10px;
		margin: 0 0 0.5rem;
	}

	.ext-item:hover,
	.ext-item[open] {
		border-color: color-mix(in oklab, var(--color-brand-mint) 40%, transparent);
	}

	.ext-item summary {
		list-style: none;
		cursor: pointer;
		font-size: 0.88rem;
		line-height: 1.4;
		padding: 0.55rem 1.6rem 0.55rem 0.75rem;
		position: relative;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.ext-item summary::-webkit-details-marker {
		display: none;
	}

	.ext-item summary::after {
		content: '+';
		position: absolute;
		right: 0.6rem;
		top: 50%;
		transform: translateY(-50%);
		font-family: var(--font-mono), monospace;
		color: var(--color-brand-mint);
		transition: transform var(--motion-min-ms) var(--ease-out-quint);
	}

	.ext-item[open] summary::after {
		transform: translateY(-50%) rotate(45deg);
	}

	.ext-main {
		margin: 0 0 0.35rem;
		padding: 0 0.75rem;
		font-size: 0.9rem;
		line-height: 1.5;
	}

	.ext-main a {
		color: var(--color-brand-mint);
	}

	.ext-hint {
		margin: 0;
		padding: 0 0.75rem 0.65rem;
		font-size: 0.82rem;
		opacity: 0.7;
		line-height: 1.5;
	}
</style>
